#!/bin/bash

cd $(dirname $0)/..

. ./scripts/version.sh

ROOT_VERSION=v0.4.1
TRAEFIK_VERSION=1.81.0
CHARTS_DIR=build/static/charts

mkdir -p ${CHARTS_DIR}

curl --compressed -sfL https://github.com/Oats87/k3s-root/releases/download/nft/k3s-root-amd64.tar | tar xf -
ln -sf pigz bin/unpigz
mkdir -p bin/aux && rm bin/mount && ln -sf ../busybox bin/aux/mount

TRAEFIK_FILE=traefik-${TRAEFIK_VERSION}.tgz
curl -sfL https://kubernetes-charts.storage.googleapis.com/${TRAEFIK_FILE} -o ${CHARTS_DIR}/${TRAEFIK_FILE}

cp scripts/wg-add.sh bin/aux/
